// ADD A PRIVATE FUNCTION CALLED CALCULATE

// ADD FOUR PUBLIC FUNCTIONS BELOW

// ADD FUNCTION

// SUBTRACT FUNCTION

// MULTIPLY FUNCTION

// DIVIDE FUNCTION

// EXPORT THE FOUR PUBLIC FUNCTIONS